# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threadsApp', '0003_auto_20161124_1006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='ThreadSubject',
        ),
    ]
